### ISSUE TITLE
Antminer S7, S9, L3+ support

### ISSUE THREAD

**Issue by anselal** [johnnyblissdev/AntViewer#1]
I used to this software a while ago to connect to my S3 and it worked just fine, but it wont connect to any newer models. I think that the API has changed since the newer machines use bmminer (S9) and cgminer (S7 & L3+).
Is there a way you could apply some changes to your code to support the newer versions of antminers ???

**Comment by johnnyblissdev** [comment]
sorry, i don't do any mining anymore. feel free to use code however you want
